/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ClasesPrincipales;

import javax.swing.JFrame;

/**
 *
 * @author carne
 */
public class Terminal extends javax.swing.JFrame {

    /**
     * Creates new form Terminal
     */
    public JFrame pantallaAparcar = new JFrame();
    public JFrame pantallaRetirar = new JFrame();
    
    public Terminal() {
        initComponents();
        ventanaParquimetro();
        setLocation();
    }

    public void setLocation() {
        this.setLocationRelativeTo(null);
    }

    public void ventanaParquimetro() {
        LabelParquimetroPrincipal.setSize(350, 720);
        setContentPane(LabelParquimetroPrincipal);
        LabelParquimetroPrincipal.add(BotonAparcarCoche);
        LabelParquimetroPrincipal.add(BotonRetirarCoche);
        LabelParquimetroPrincipal.add(LabelPlaceHolderTabla);

        BotonAparcarCoche.setSize(250, 40);
        BotonRetirarCoche.setSize(250, 40);
        LabelPlaceHolderTabla.setSize(237, 175);

        BotonAparcarCoche.setBounds(50, 500, BotonAparcarCoche.getWidth(), BotonAparcarCoche.getHeight());
        BotonRetirarCoche.setBounds(50, 550, BotonRetirarCoche.getWidth(), BotonRetirarCoche.getHeight());
        LabelPlaceHolderTabla.setBounds(56, 272, LabelPlaceHolderTabla.getWidth(), LabelPlaceHolderTabla.getHeight());
    }

    public void ventanaAparcar() {

    }

    public void ventanaRetirar() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelParquimetroPrincipal = new javax.swing.JLabel();
        BotonAparcarCoche = new javax.swing.JButton();
        BotonRetirarCoche = new javax.swing.JButton();
        LabelPlaceHolderTabla = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(365, 755));
        setMinimumSize(new java.awt.Dimension(365, 755));
        setPreferredSize(new java.awt.Dimension(365, 755));
        setResizable(false);

        LabelParquimetroPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourcesFotos/Parquimetro_Parking3(350x720).png"))); // NOI18N
        LabelParquimetroPrincipal.setText("jLabel1");

        BotonAparcarCoche.setText("Aparcar coche");

        BotonRetirarCoche.setText("Retirar coche");

        LabelPlaceHolderTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resourcesFotos/Victor2(500x500).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(LabelPlaceHolderTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 274, Short.MAX_VALUE)
                .addComponent(LabelParquimetroPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAparcarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonRetirarCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(LabelParquimetroPrincipal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(BotonAparcarCoche)
                        .addGap(43, 43, 43)
                        .addComponent(BotonRetirarCoche))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(LabelPlaceHolderTabla)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Terminal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Terminal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAparcarCoche;
    private javax.swing.JButton BotonRetirarCoche;
    private javax.swing.JLabel LabelParquimetroPrincipal;
    private javax.swing.JLabel LabelPlaceHolderTabla;
    // End of variables declaration//GEN-END:variables
}
